name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        device: [d1, d1xks, d2x, d2s, d2xks]
    runs-on: ubuntu-24.04

    steps:
      - name: "⏰Set Time Zone to Beijing"
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: "🚄Set up build environment"
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core flex bison build-essential zip curl \
          zlib1g-dev libc6-dev-i386 lib32z1-dev unzip

      - name: "⭐Checkout repository with submodules"
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: "💡 Setup KernelSu"
        run: |
          if [ -d "./KernelSU-Next" ]; then rm -rf "./KernelSU-Next"; fi
          if [ -d "./drivers/KernelSU-Next" ]; then rm -rf "./drivers/KernelSU-Next"; fi 
          curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/susfs-rksu-master/kernel/setup.sh" | bash -s susfs-rksu-master

      - name: "🐎Build for specific device"
        run: ./build.sh -m ${{ matrix.device }} -k Y -r N

      - name: "💫Prepare ZIP files for upload"
        run: |
          mkdir -p ${{ github.workspace }}/build/out/zip_files
          find ${{ github.workspace }}/build/out/ -type f -name "*.zip" -exec cp {} ${{ github.workspace }}/build/out/zip_files/ \;

      - name: "😎Upload ZIP files as artifact"
        uses: actions/upload-artifact@v4
        with:
         name: "ExtremeKRNL-Nexus-Susfs-${{ matrix.device }}"
         path: ${{ github.workspace }}/build/out/zip_files/
